'use strict';

const Discord = require('discord.js');
const config = require('../config');

class ReactionHandler {
    /**
     * Returns an object contains a boolean indicating whether or not it passed the check and a function if it passed
     * @param {Discord.MessageReaction} messageReaction the reaction generated by the user
     * @returns {{handle: Function|undefined, passed: boolean}} an object contains a boolean indicating whether or not it passed the check and a function if it passed
     */
    static check(messageReaction) {
        const obj = {};
        if (messageReaction.message.embeds.length > 0) {
            obj.handle = handleEmbed;
            obj.passed = true;
        } else if (messageReaction.message.content.length > 0) {
            obj.handle = handleMessage;
            obj.passed = true;
        } else {
            obj.passed = false;
        }
        return obj;
    }
}

/**
 * Returns true if the reaction was properly handled, false otherwise
 * @param {Discord.MessageReaction} messageReaction the reaction generated by the user
 * @param {Discord.User} user the user
 * @param {boolean} add indicates whether or not the reaction was added or removed
 * @returns {boolean} true if the reaction was properly handled, false otherwise
 */
const handleEmbed = (messageReaction, user, add) => {
    const embed = messageReaction.message.embeds[0];
    const [type, title] = embed.title.split('|').map(val => val.trim());
    if (config.embedTypes[type] && config.embedTypes[type].has(title))
        return config.embedTypes[type].get(title).handleReaction(messageReaction, user, add);
    return false;
};

/**
 * Returns true if the reaction was properly handled, false otherwise
 * @param {Discord.MessageReaction} messageReaction the reaction generated by the user
 * @param {Discord.User} user the user
 * @param {boolean} add indicates whether or not the reaction was added or removed
 * @returns {boolean} true if the reaction was properly handled, false otherwise
 */
const handleMessage = (messageReaction, user, add) => {
    return false;
};

module.exports = ReactionHandler;